"use client";

import { useEffect, useRef, useState } from "react";
import {
  Image,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from "react-native";
import { useRouter } from "expo-router";
import { SafeAreaProvider } from "react-native-safe-area-context";

import { aiChatAssistant } from "@/constants/aiChatAssistant";

interface Message {
  id: string;
  type: "user" | "ai";
  content: string;
  timestamp: Date;
}

export default function AIChatAssistant() {
  const router = useRouter();
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "1",
      type: "user",
      content: "Explain quantum computing in simple terms",
      timestamp: new Date(),
    },
    {
      id: "2",
      type: "ai",
      content:
        'As an AI, I don\'t have real-time access to IMDb\'s rankings, and my training only goes up until September 2021. However, I can provide you with a list of critically acclaimed movies that were highly rated at that time. Please note that opinions on the "best" movies can vary, and IMDb ratings may change over time. Here are ten highly regarded films as of September 2021:\n\n1. "The Shawshank Redemption" (1994)\n2. "The Godfather" (1972)\n3. "The Godfather: Part II" (1974)\n4. "The Dark Knight" (2008)\n5. "Pulp Fiction" (1994)\n6. "Schindler\'s List" (1993)',
      timestamp: new Date(),
    },
  ]);
  const [inputText, setInputText] = useState("");
  const scrollViewRef = useRef<ScrollView>(null);

  useEffect(() => {
    scrollViewRef.current?.scrollToEnd({ animated: true });
  }, [messages]);

  const handleSendMessage = () => {
    if (inputText.trim() === "") {
      return;
    }

    const newMessage: Message = {
      id: Date.now().toString(),
      type: "user",
      content: inputText,
      timestamp: new Date(),
    };

    setMessages([...messages, newMessage]);
    setInputText("");

    setTimeout(() => {
      const aiResponse: Message = {
        id: (Date.now() + 1).toString(),
        type: "ai",
        content:
          "This is a sample AI response. In a real implementation, this would be generated by an AI model.",
        timestamp: new Date(),
      };

      setMessages((prev) => [...prev, aiResponse]);
    }, 500);
  };

  const handleCopyMessage = (content: string) => {
    console.log("[v0] Copied message:", content);
  };

  const handleShareMessage = (content: string) => {
    console.log("[v0] Sharing message:", content);
  };

  const handleRegenerateResponse = () => {
    const lastMessageIndex = messages.length - 1;

    if (messages[lastMessageIndex]?.type === "ai") {
      setMessages((prev) => prev.slice(0, -1));

      setTimeout(() => {
        const aiResponse: Message = {
          id: (Date.now() + 1).toString(),
          type: "ai",
          content: "This is a regenerated AI response with different content.",
          timestamp: new Date(),
        };

        setMessages((prev) => [...prev, aiResponse]);
      }, 500);
    }
  };

  return (
    <SafeAreaProvider style={styles.safeArea}>
      {/* Header */}
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} style={styles.backButton}>
          <Text style={styles.backButtonText}>{"<"}</Text>
        </Pressable>
        <Text style={styles.headerTitle}>AI Chat Assistant</Text>
        <View style={styles.headerSpacer} />
      </View>

      {/* Chat */}
      <KeyboardAvoidingView
        behavior={Platform.OS === "ios" ? "padding" : "height"}
        style={styles.keyboardContainer}
      >
        <ScrollView
          ref={scrollViewRef}
          style={styles.messagesContainer}
          contentContainerStyle={styles.messagesContent}
        >
          {messages.map((message) => (
            <View key={message.id} style={styles.messageWrapper}>
              {message.type === "user" ? (
                <View style={styles.messageRow}>
                  <Image source={aiChatAssistant.women} style={styles.userAvatar} />
                  <View style={styles.userBubble}>
                    <Text style={styles.messageText}>{message.content}</Text>
                    <Pressable
                      onPress={() => handleCopyMessage(message.content)}
                      style={styles.iconButton}
                    >
                      <Image source={aiChatAssistant.copy} style={styles.copyIcon} />
                    </Pressable>
                  </View>
                </View>
              ) : (
                <View style={styles.messageRow}>
                  <Image source={aiChatAssistant.aiMagic} style={styles.aiAvatar} />
                  <View style={styles.aiBubble}>
                    <Text style={styles.messageText}>{message.content}</Text>
                    <View style={styles.aiActions}>
                      <Pressable
                        onPress={() => handleCopyMessage(message.content)}
                        style={styles.smallIconButton}
                      >
                        <Image source={aiChatAssistant.copy} style={styles.smallIcon} />
                      </Pressable>
                      <Pressable
                        onPress={() => handleShareMessage(message.content)}
                        style={styles.smallIconButton}
                      >
                        <Image
                          source={aiChatAssistant.solarShareLinear}
                          style={styles.smallIcon}
                        />
                      </Pressable>
                    </View>
                  </View>
                </View>
              )}
            </View>
          ))}
        </ScrollView>

        {/* Regenerate */}
        <View style={styles.regenerateContainer}>
          <Pressable
            onPress={handleRegenerateResponse}
            style={styles.regenerateButton}
          >
            <Image
              source={aiChatAssistant.codeCompare}
              style={styles.regenerateIcon}
            />
            <Text style={styles.regenerateText}>Regenerate Response</Text>
          </Pressable>
        </View>

        {/* Input */}
        <View style={styles.inputContainer}>
          <TextInput
            style={styles.input}
            placeholder="Send a message"
            placeholderTextColor="#bbb"
            value={inputText}
            onChangeText={setInputText}
            multiline
            maxLength={500}
          />
          <Pressable onPress={handleSendMessage} style={styles.sendButton}>
            <Image source={aiChatAssistant.vector} style={styles.sendIcon} />
          </Pressable>
        </View>
      </KeyboardAvoidingView>
    </SafeAreaProvider>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e5e5",
  },
  backButton: {
    padding: 8,
  },
  backButtonText: {
    fontSize: 24,
    color: "#333",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    flex: 1,
    textAlign: "center",
  },
  headerSpacer: {
    width: 40,
  },
  keyboardContainer: {
    flex: 1,
  },
  messagesContainer: {
    flex: 1,
  },
  messagesContent: {
    paddingHorizontal: 12,
    paddingVertical: 16,
  },
  messageWrapper: {
    marginBottom: 16,
  },
  messageRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  userAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  aiAvatar: {
    width: 20,
    height: 20,
    marginRight: 12,
    marginTop: 4,
  },
  userBubble: {
    flex: 1,
    backgroundColor: "#e8f0f7",
    borderRadius: 12,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  aiBubble: {
    flex: 1,
    backgroundColor: "#f0e8f8",
    borderRadius: 12,
    padding: 12,
  },
  messageText: {
    fontSize: 14,
    color: "#333",
    lineHeight: 20,
    flex: 1,
  },
  iconButton: {
    marginLeft: 8,
    padding: 4,
  },
  copyIcon: {
    width: 20,
    height: 20,
  },
  aiActions: {
    flexDirection: "row",
    marginTop: 8,
    justifyContent: "flex-start",
    gap: 8,
  },
  smallIconButton: {
    padding: 4,
  },
  smallIcon: {
    width: 18,
    height: 18,
  },
  regenerateContainer: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  regenerateButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ddd",
    gap: 8,
  },
  regenerateIcon: {
    width: 16,
    height: 16,
  },
  regenerateText: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderTopColor: "#e5e5e5",
    gap: 8,
  },
  input: {
    flex: 1,
    backgroundColor: "#f5f5f5",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 14,
    color: "#333",
    maxHeight: 100,
  },
  sendButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  sendIcon: {
    width: 20,
    height: 20,
  },
});
